# Generated by Django 5.1.6 on 2026-03-09 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('First Drop', 'First Drop'), ('5 Lives Saved', '5 Lives Saved'), ('Lifesaver Hero', 'Lifesaver Hero')], max_length=20)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['awarded_at'],
                'unique_together': {('user', 'badge_type')},
            },
        ),
    ]
