# Generated by Django 5.1.6 on 2026-03-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_donorbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='next_eligible_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
