# Generated by Django 5.1.6 on 2026-03-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_bloodrequest_updated_at_donationcamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Fulfilled', 'Fulfilled'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='requesttimelineevent',
            name='status_snapshot',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Fulfilled', 'Fulfilled'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], max_length=10),
        ),
    ]
