# Generated by Django 5.1.6 on 2026-03-09 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_bloodrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrecord',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_records', to='donations.bloodrequest'),
        ),
    ]
